all: testCircle testMatrix randomVertices

testCircle: lengthOfShortestPathCircle.cpp
	g++ lengthOfShortestPathCircle.cpp -o testCircle

testMatrix: numberOfShortestPathsMatrix.cpp
	g++ numberOfShortestPathsMatrix.cpp -o testMatrix

randomVertices: randomVertices.cpp
	g++ randomVertices.cpp -o randomVertices

clean:
	rm testCircle testMatrix randomVertices